### ISSUE TITLE
Prettier Extension URL

### ISSUE THREAD

**Issue by omer-pon** [pondevelopment/pon-developer-guide#9]
Under Generic development in README.md, the URL of prettier is one which is depreciated. We can update it with the new URL which is => https://marketplace.visualstudio.com/items?itemName=esbenp.prettier-vscode. I couldn't create a PR since I don't have right to do so.

https://github.com/pondevelopment/pon-developer-guide/blob/9a8cf6bf44b721c36f89347102f059ba49e8a68d/README.md?plain=1#L24

**Comment by roy-pon** [comment]
Good one created a PR for this
https://github.com/pondevelopment/pon-developer-guide/pull/10

**Comment by roy-pon** [comment]
Fixed in https://github.com/pondevelopment/pon-developer-guide/pull/10
